### ISSUE TITLE
Invalid SSL

### ISSUE THREAD

**Issue by rhino-corey** [ps1dr3x/wordpress-docker-fullstack-dev#1]
Is there a way to configure the DockerFile to generate an SSL for localhost that will not throw validation warnings in Chrome?

**Comment by micene09** [comment]
Maybe with a self signed cert and some os related hack (not so easy and dev friendly, need to go deeper about it)...

Keep in mind that this is a template/starter-kit for general purpose WordPress projects, you don't need to have a valid cert on your localhost in a dev phase, but this is just my opinion.

**Comment by ps1dr3x** [comment]
The usual way to achieve this for localhost is to generate a self-signed certificate and trust it in your operating system’s trust store. By the way, as @Micene09 said, you generally don't need to have a valid certificate in development.
Check this article by Let's Encrypt:
https://letsencrypt.org/docs/certificates-for-localhost/
